### ISSUE TITLE
Integrate your setup system as a module in doom-emacs

### ISSUE THREAD

**Issue by pashazz** [Lambda-Emacs/lambda-emacs#1]
Hello!

You may know about https://github.com/doomemacs/doomemacs

It would be great if you would integrate your setup (i.e. theme and modeline, defaults) as a Doom module so that user could enable it in his init.el easily without breaking  other configurations

Thank you. I could help you with the module if you want

**Comment by mclearc** [comment]
Since I don't use Doom I wouldn't really know how to configure a module for it. And it isn't clear to me that the config in lambda-emacs integrates well with doom since they both have their own internal config structure. That said, individual functions and settings are easily ported over. So if you have specific interests I would say that you should look at the relevant file in the [library](https://github.com/Lambda-Emacs/lambda-emacs/tree/main/.local/lambda-library/lambda-setup). You should be able to use the themes and lambda-line with Doom though without much hassle (assuming doom uses standard ways of calling themes, etc.).
